name: lce-release

on:
  release:
    types: [published]
    tags:
      - v*
  push:
    branches:
      - "releases/nightly"

env:
  IMAGE_NAME: dev

jobs:
  windows-release-wheel:
    name: Build release wheels for Windows
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Set up MSVC CMD x86_64
        uses: ilammy/msvc-dev-cmd@v1
      - name: Build Windows wheels
        run: |
          export PYTHON_BIN_PATH=$(which python)

          mkdir C:/bazel_cache

          python --version
          python -m pip install wheel setuptools numpy six --no-cache-dir

          ./configure.sh

          bazelisk --output_base=C:/bazel_cache build :build_pip_pkg --copt=/arch:AVX --enable_runfiles --define=override_eigen_strong_inline=true --discard_analysis_cache --nokeep_state_after_build --notrack_incremental_state
          bazel-bin/build_pip_pkg wheelhouse

        shell: bash
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-wheels
          path: wheelhouse
